/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
    './src/errors/*.{ts,tsx}'
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1280px",
      },
    },
    extend: {
      colors: {
        primary: 'var(--md-sys-color-primary)',
        surfacetint: 'var(--md-sys-color-surface-tint)',
        onprimary: 'var(--md-sys-color-on-primary)',
        primary_container: 'var(--md-sys-color-primary-container)',
        onprimary_container: 'var(--md-sys-color-on-primary-container)',
        secondary: 'var(--md-sys-color-secondary)',
        onsecondary: 'var(--md-sys-color-on-secondary)',
        secondary_container: 'var(--md-sys-color-secondary-container)',
        onsecondary_container: 'var(--md-sys-color-on-secondary-container)',
        tertiary: 'var(--md-sys-color-tertiary)',
        ontertiary: 'var(--md-sys-color-on-tertiary)',
        tertiary_container: 'var(--md-sys-color-tertiary-container)',
        ontertiary_container: 'var(--md-sys-color-on-tertiary-container)',
        error: 'var(--md-sys-color-error)',
        onerror: 'var(--md-sys-color-on-error)',
        error_container: 'var(--md-sys-color-error-container)',
        onerror_container: 'var(--md-sys-color-on-error-container)',
        background: 'var(--md-sys-color-background)',
        onbackground: 'var(--md-sys-color-on-background)',
        surface: 'var(--md-sys-color-surface)',
        onsurface: 'var(--md-sys-color-on-surface)',
        surface_variant: 'var(--md-sys-color-surface-variant)',
        onsurface_variant: 'var(--md-sys-color-on-surface-variant)',
        outline: 'var(--md-sys-color-outline)',
        outline_variant: 'var(--md-sys-color-outline-variant)',
        shadow: 'var(--md-sys-color-shadow)',
        scrim: 'var(--md-sys-color-scrim)',
        inverse_surface: 'var(--md-sys-color-inverse-surface)',
        inverse_on_surface: 'var(--md-sys-color-inverse-on-surface)',
        inverse_primary: 'var(--md-sys-color-inverse-primary)',
        primary_fixed: 'var(--md-sys-color-primary-fixed)',
        onprimary_fixed: 'var(--md-sys-color-on-primary-fixed)',
        primary_fixed_dim: 'var(--md-sys-color-primary-fixed-dim)',
        onprimary_fixed_variant: 'var( --md-sys-color-on-primary-fixed-variant)',
        secondary_fixed: 'var(--md-sys-color-secondary-fixed)',
        onsecondary_fixed: 'var(--md-sys-color-on-secondary-fixed)',
        secondary_fixed_dim: 'var(--md-sys-color-secondary-fixed-dim)',
        onsecondary_fixed_variant: 'var( --md-sys-color-on-secondary-fixed-variant)',
        tertiary_fixed: 'var(--md-sys-color-tertiary-fixed)',
        ontertiary_fixed: 'var(--md-sys-color-on-tertiary-fixed)',
        tertiary_fixed_dim: 'var(--md-sys-color-tertiary-fixed-dim)',
        ontertiary_fixed_variant: 'var( --md-sys-color-on-tertiary-fixed-variant)',
        surface_dim: 'var(--md-sys-color-surface-dim)',
        surface_bright: 'var(--md-sys-color-surface-bright)',
        surface_container_lowest: 'var(--md-sys-color-surface-container-lowest)',
        surface_container_low: 'var(--md-sys-color-surface-container-low)',
        surface_container: 'var(--md-sys-color-surface-container)',
        surface_container_high: 'var(--md-sys-color-surface-container-high)',
        surface_container_highest: 'var(--md-sys-color-surface-container-highest)',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require('@tailwindcss/typography'),
  ],
}