[tool.poetry]
name = "initialization"
version = "0.1.0"
description = ""
authors = ["Muhammad Reza Fatehinia <fatehinia@amnafzar.ir>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.11"
chromadb-client = "^0.6.0"
minio = "^7.2.13"
hazm = "^0.10.0"
psycopg = {extras = ["binary"], version = "^3.2.3"}
sqlalchemy = "^2.0.36"
beanie = "^1.28.0"
persiantools = "^5.1.0"
phonenumbers = "^8.13.52"
scipy = "~1.10.1"
pandas = "^2.2.3"
xlrd = "^2.0.1"
fastapi = "^0.115.8"
chainlit = "^2.1.0"
langchain-core = "^0.3.33"
langchain-openai = "^0.3.3"
langchain = "^0.3.17"
langchain-chroma = "^0.2.1"
llama-parse = "^0.5.20"
requests = "^2.32.3"
pypdf2 = "^3.0.1"
pdf2image = "^1.17.0"
poppler-utils = "^0.1.0"
docx = "^0.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
